[View in Colaboratory](https://colab.research.google.com/github/kurikei/google-colab-sandbox/blob/master/website/github.com/rougier/numpy-100/100_Numpy_exercises.ipynb)

# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [0]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [6]:
print(np.__version__)
np.show_config() # need ()

1.14.5
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    define_macros = [('HAVE_CBLAS', None)]
    language = c
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    define_macros = [('HAVE_CBLAS', None)]
    language = c
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    define_macros = [('HAVE_CBLAS', None)]
    language = c
blis_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    define_macros = [('HAVE_CBLAS', None)]
    language = c
lapack_mkl_info:
  NOT AVAILABLE
blas_mkl_info:
  NOT AVAILABLE


#### 3. Create a null vector of size 10 (★☆☆)

In [9]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆)

In [20]:
array_1d = np.zeros(10)
print(array_1d)
print("%d bytes" % (array_1d.itemsize * array_1d.size))

array_2d = np.zeros((10,10))
print(array_2d)
print("%d bytes" % (array_2d.itemsize * array_2d.size))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
80 bytes
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
800 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

ERROR:root:File `u'`which.py'` not found.


#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [24]:
ndarray = np.zeros(10)
ndarray[4] = 1
print(ndarray)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [60]:
ndarray = np.arange(10, 50)
print(ndarray)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [33]:
ndarray = np.arange(1, 11)
print(ndarray)

reverse_ndarray = ndarray[::-1]
print(reverse_ndarray)

[ 1  2  3  4  5  6  7  8  9 10]
[10  9  8  7  6  5  4  3  2  1]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [63]:
ndarray = np.arange(0, 9)
matrix_3x3 = np.reshape(ndarray, (3, 3))
print(matrix_3x3)

another_matrix_3x3 = np.arange(9).reshape(3, 3)
print(another_matrix_3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [64]:
src_array = np.array([1,2,0,0,4,0])
zero_indices = np.nonzero(src_array)
print(zero_indices)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [65]:
matrix_3x3 = np.eye(3)
print(matrix_3x3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [66]:
matrix_3x3x3 = np.random.random((3, 3, 3))
print(matrix_3x3x3)

[[[0.8267448  0.81013545 0.84167809]
  [0.73703901 0.08216136 0.11856995]
  [0.8456487  0.93332717 0.47685408]]

 [[0.63841122 0.63187385 0.50247846]
  [0.78970882 0.72007328 0.68471875]
  [0.58964819 0.31625361 0.92569722]]

 [[0.09324577 0.68860905 0.24548706]
  [0.97895456 0.7470034  0.97069672]
  [0.93640537 0.65512463 0.58288581]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [68]:
src_array = np.random.random((10, 10))
print(src_array)
print(np.min(src_array))
print(np.max(src_array))

# another answer
print(src_array.min())
print(src_array.max())

[[0.61132628 0.41449027 0.44187862 0.60040613 0.80221446 0.441484
  0.8682671  0.39808313 0.51935954 0.10009292]
 [0.86251733 0.87251331 0.01963874 0.68365018 0.64244504 0.09460722
  0.36018857 0.40386353 0.19004534 0.14870264]
 [0.86542472 0.04807106 0.1757919  0.18730479 0.61953584 0.97610616
  0.51667866 0.50771826 0.66920379 0.44583031]
 [0.93937301 0.02638193 0.12836161 0.15889538 0.30660798 0.08545512
  0.10434639 0.99294763 0.35729653 0.01547994]
 [0.46123813 0.70074164 0.89103228 0.60373192 0.98259274 0.06594001
  0.45821737 0.40039594 0.16024908 0.83364872]
 [0.85813639 0.53958291 0.62228744 0.4842655  0.73910567 0.07507988
  0.40400069 0.57849542 0.61032868 0.73233624]
 [0.59712935 0.18885938 0.37758934 0.9690711  0.66013368 0.01544451
  0.87974325 0.0132901  0.21184002 0.62527111]
 [0.93441895 0.91954156 0.46917445 0.64365439 0.10972097 0.14540974
  0.27894051 0.54273874 0.36674678 0.22280749]
 [0.55776214 0.1024437  0.47448911 0.58635874 0.59122691 0.58338922
  0.05969133 0

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [72]:
src_array = np.random.random(30)
print(src_array)

print(np.mean(src_array))

# another answer
print(src_array.mean())

[0.57025386 0.04277437 0.66262992 0.9708439  0.38067754 0.55928715
 0.25246034 0.14129069 0.5659464  0.00767915 0.38866206 0.02748391
 0.76835166 0.47867009 0.86608228 0.09429721 0.76208428 0.10224372
 0.63303454 0.18247747 0.1916161  0.07495727 0.35806548 0.16432479
 0.16542108 0.6952303  0.68149951 0.62275009 0.27736945 0.7485391 ]
0.4145667909381549
0.4145667909381549


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [80]:
array_2d = np.ones((4,4))
print(array_2d)

array_2d[1:-1,1:-1] = 0
print(array_2d)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [84]:
array_2x2 = np.ones((2,2))
print(array_2x2)

array_3x3 = np.pad(array_2x2, pad_width=1, mode='constant', constant_values=0)
print(array_3x3)

[[1. 1.]
 [1. 1.]]
[[0. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [98]:
print(0 * np.nan) # nan
print(np.nan == np.nan) # False
print(np.inf > np.nan) # False
print(np.nan - np.nan) # nan
print(0.3 == 3 * 0.1) # False

# nan calc result
print('=== nan calc result ===')
print(np.nan + 2) # nan
print(np.nan - 2) # nan
print(np.nan * 2) # nan
print(np.nan / 2) # nan
print(np.nan % 2) # nan
print(np.nan // 2) # nan
print(np.nan ** 2) # nan
print(np.nan + np.nan) # nan
print(np.nan - np.nan) # nan
print(np.nan * np.nan) # nan
print(np.nan / np.nan) # nan
print(np.nan % np.nan) # nan
print(np.nan // np.nan) # nan
print(np.nan ** np.nan) # nan
print(np.nan > 0) # False
print(np.nan == 0) # False
print(np.nan < 0) # False
print(np.nan == np.nan) # False

# inf calc result
print('=== inf calc result ===')
print(np.inf + 2) # inf
print(np.inf - 2) # inf
print(np.inf * 2) # inf
print(np.inf / 2) # inf
print(np.inf % 2) # nan
print(np.inf // 2) # nan
print(np.inf - np.inf) # nan
print(np.inf / np.inf) # nan

nan
False
False
nan
False
=== nan calc result ===
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
False
False
False
False
=== inf calc result ===
inf
inf
inf
inf
nan
nan
nan
nan


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

#### 22. Normalize a 5x5 random matrix (★☆☆)

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)